server:
  servlet:
    encoding:
      charset: utf-8
      force: true
    # url rewrite 문제 해결
    session:
      tracking-modes: cookie
  port: 5000

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:mysql://localhost:3306/blogdb
    username: metacoding
    password: metachoding1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 10
        dialect: org.hibernate.dialect.MysqlDialect
    open-in-view: false

logging:
  level:
    org.hibernate.orm.jdbc.bind: INFO
    shop.mtcoding.blog: INFO